version: '2'

services:

  app:
    # Build image using the folowing Dockerfile:
    build: 
      context: .
      dockerfile: Dockerfile
    # Name of the image to be built:
    image: ImageName
  
  # USAGE: docker-compose -f docker-compose-test-local-predeployment.yml run --rm unitTests
  unitTests:
    # get image from docker respiratory:
    image: node:latest
    # Where does it mount !>?
    volumes:
      # Volume attached to the host through docker-machine VM.
      - ../:/app
    # entrypoint allows cd command to work, in command: bash it doesn't.
    entrypoint: "/app/setup/shellScript/testAndBuild.sh"
    working_dir: /app
    # use /bin/sh where bash is not installed (i.e. alpine-node image). Installed bash to the default image.
    command: bash -c ""


